name: energiefixers071
description: "EnergieFixers071 Volunteer Management System - Flutter Edition"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  
  # Navigation & State Management
  go_router: ^16.0.0
  riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10
  
  # Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  
  # Network & HTTP
  http: ^1.2.0
  dio: ^5.4.0
  
  # Data Serialization
  json_annotation: ^4.8.1
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # File System & Path
  path_provider: ^2.1.2
  
  # Date & Time
  intl: ^0.20.0
  
  # Forms & Validation
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.0.1
  
  # UI Components
  data_table_2: ^2.5.11
  fl_chart: ^1.0.0
  adaptive_dialog: ^2.0.0
  
  # Images & Assets
  flutter_svg: ^2.0.9
  
  # Development
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
